export const ROUTES = {
  HOME: "/",
  IMPACT: "/impact",
  SEARCH: "/search",
  STORY: "/story",
  BEAUTY_AND_COSMETICS: "/beauty-and-cosmetics",
  AUTHENTIC_FOODS: "/authentic-foods",
  PRODUCT_DETAIL: "/product-detail",
  CHECKOUT: "/checkout",
  PARTNERS: "/partners",
  CART: "/cart",
  SHIPPING_FEES: "/shipping-fees",
  TERMS_CONDITIONS: "/terms-conditions",
  PRIVACY_POLICY: "/privacy-policy",
  SHIPPING_RETURNS: "/shipping-returns",
  REFUND: "/refund",
  SUCCESS_CHECKOUT: "/checkout/success",
  AUTH: {
    ROOT: "/auth",
    FORGET_PASSWORD: "/auth/forget-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  WISHLIST: "/wishlist",
  USER: {
    ACCOUNT: "/account",
    ORDERS: "/account/orders",
    PERSONAL_DETAILS: "/account/personal-details",
    ADDRESS_BOOK: "/account/address-book",
    PAYMENT_METHODS: "/account/payment-methods",
    SHOP: "/account/shop",
    LIST_PRODUCTS: "/account/list-products",
    PURCHASE_AND_REVIEWS: "/account/purchase_and_reviews",
  },
  SELLERS: {
    HOME: "/sellers",
    REGISTER: "/sellers/register",
    ADD_LISTING: "/sellers/add-listing",
  },
};
